kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "simpleapp.fullname" . }}-config
data:
  application.yml: |-
    spring:
      application:
        name: {{ template "simpleapp.name" . }}-config