kind: ConfigMap
apiVersion: v1
metadata:
  name: simpleapp
data:
  application.yml: |-
    spring:
      application:
{{- if .Values.service.name }}
        name: {{ .Values.service.name }}
{{- else }}
        name: {{ template "simpleapp.fullname" . }}
{{- end }}