kind: ConfigMap
apiVersion: v1
metadata:
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ template "fullname" . }}
{{- end }}
data:
  application.yml: |-
    spring:
      application:
{{- if .Values.service.name }}
        name: {{ .Values.service.name }}
{{- else }}
        name: {{ template "fullname" . }}
{{- end }}