apiVersion: v1
kind: Endpoints
metadata:
  name: external-lolol-service
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
subsets:
  - addresses:
      - ip: "86.252.215.117"
    ports:
      -
        name: "https"
        port: 443