management:
  endpoint:
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,restart,metrics
      base-path: /
  metrics:
    tags:
      application: ${spring.application.name}
