management:
  endpoint:
    restart:
      enabled: true
    configprops:
      enabled: true
    env:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,restart,configprops,env
      base-path: /
      path-mapping:
        prometheus: metrics
  metrics:
    tags:
      application: ${spring.application.name}