
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,restart
      base-path: /
      path-mapping:
        prometheus: metrics
  metrics:
    tags:
      application: ${spring.application.name}